import Link from 'next/link';
import { notFound } from 'next/navigation';
import { ArrowLeft, ArrowUpRight, Code2 } from 'lucide-react';
import { members } from '@/data/members';
import { Avatar } from '@/components/yearbook';
export function generateStaticParams() { return members.map(m => ({ id: m.id })); }
export async function generateMetadata({ params }: { params: Promise<{id:string}> }) { const {id}=await params;const member=members.find(m=>m.id===id);return { title: member ? `${member.nickname} — CS66` : 'ไม่พบสมาชิก — CS66', description:member?.quote }; }
export default async function MemberPage({ params }: { params: Promise<{id:string}> }) {
 const {id}=await params;const index=members.findIndex(m=>m.id===id);if(index<0)notFound();const member=members[index];const prev=members[(index+members.length-1)%members.length];const next=members[(index+1)%members.length];
 return <main className="profile-page container"><header className="profile-header"><Link href="/#members"><ArrowLeft size={16}/> กลับไปหาเพื่อน CS66</Link><Link href="/" className="brand"><Code2/><b>CS66.</b></Link></header><div className="profile-detail"><div><Avatar member={member} large/><p className="data-note">โปรไฟล์ตัวอย่าง · เปลี่ยนเป็นข้อมูลและรูปจริงได้ใน members.ts</p></div><div className="profile-details"><div className="section-kicker">เพื่อนในรุ่น / CS66 / {String(index+1).padStart(2,'0')}</div><span className="role" style={{color:member.color}}>{member.role}</span><h1 className="section-title">{member.nickname}<span>.</span></h1><h2>{member.fullname}</h2><div className="profile-facts"><div><span>รหัสนักศึกษา</span>{member.studentId}</div><div><span>รุ่น</span>วิทยาการคอมพิวเตอร์ 66</div>{member.birthday&&<div><span>วันเกิด</span>{member.birthday}</div>}</div><h2>เกี่ยวกับฉัน</h2><p>{member.about}</p><blockquote>“{member.quote}”</blockquote><h2>ทักษะและความถนัด</h2><div className="skill-badges">{member.skills.map(skill=><span key={skill}>{skill}</span>)}</div><h2>ช่องทางติดต่อ</h2><div className="social-links">{Object.entries(member.social).filter(([,url])=>url).length ? Object.entries(member.social).filter(([,url])=>url).map(([name,url])=><a key={name} href={url} target="_blank" rel="noopener noreferrer">{name} ↗</a>) : <span className="muted">ยังไม่ได้เพิ่มช่องทางติดต่อ</span>}</div></div></div><nav className="profile-nav" aria-label="เพื่อนคนอื่นในรุ่น"><Link href={`/members/${prev.id}`}>← {prev.nickname}</Link><Link href="/#members">เพื่อนทั้งหมด</Link><Link href={`/members/${next.id}`}>{next.nickname} →</Link></nav></main>;
}
